default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: "<%= ENV['DATABASE_NAME'] %>_development"

test:
  <<: *default
  database: "<%= ENV['DATABASE_NAME'] %>_test"

production:
  <<: *default
  host: <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  database: "<%= ENV['DATABASE_NAME'] %>_production"
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
